Repository smacademic/project-GEEKS, pull requests merged in 2019-03, with the labels that each got.

#20 Create Bug Issue Templates
  .github/ISSUE_TEMPLATE/client-bug-report.md
  .github/ISSUE_TEMPLATE/server-bug-report.md
Labels: Template

#17 Convert Branch Strategy Document into Markdown
  docs/BranchStrategy.md
Labels: Documentation

#23 Update Course Primary Key
  docs/GEEKSConceptualSchema.pdf
  docs/GEEKSLogicalSchema.docx
  src/db/createTables.sql
Labels: Code, Documentation, Error

#22 Add dos user auth
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/idea-request.md
  README.md
  docs/GEEKSConceptualSchema.pdf
  docs/GEEKSLogicalSchema.docx
  src/db/createTables.sql
  src/webapp/client/js/index.js
Labels: Code, Enhancement, Server

#25 Add Course Management DB
  src/db/addCourseMgmt.sql
Labels: Code, Enhancement

#26 Add functions to gradebookServer.js and index.js
  .github/ISSUE_TEMPLATE/client-bug-report.md
  .github/ISSUE_TEMPLATE/server-bug-report.md
  docs/BranchStrategy.md
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
Labels: Code, Enhancement

#27 Add "Add Course" feature
  src/db/addCourseMgmt.sql
  src/webapp/client/index.html
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
Labels: Client, Code, Enhancement, Server

#33 Remove course db function
  docs/GEEKSConceptualSchema.pdf
  docs/GEEKSLogicalSchema.docx
  src/db/addCourseMgmt.sql
  src/db/createTables.sql
Labels: Code, Enhancement, Server

#36 Delete Duplicate Feature Template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation, File Structure, Template

#37 Update index.js
  src/webapp/client/js/index.js
Labels: Bug, Code, High Priority, Server

#38 Remove course management api
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
Labels: Code, Enhancement, Server

#48 Fix input labels in ui
  src/db/addCourseMgmt.sql
  src/webapp/client/index.html
  src/webapp/client/js/index.js
Labels: Bug, Code, Server

#51 Added Schema Qualification to Course
  src/db/addCourseMgmt.sql
Labels: Bug, Code, Server

#52 Update addCourseMgmt.sql
  src/db/addCourseMgmt.sql
Labels: Code, Enhancement
