Repository smacademic/project-GEEKS, pull requests merged in 2019-05, with the labels that each got.

#123 Add and update Repo Documentation
  README.md
  src/db/README.md
  src/webapp/README.md
  tests/SystemTesting/README.md
Labels: DocType - Documentation, Type - Enhancement, Type - Error

#121 Added Documentation Request Template
  .github/ISSUE_TEMPLATE/client-bug-report.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/idea-request.md
  .github/ISSUE_TEMPLATE/server-bug-report.md
Labels: DocType - Documentation, DocType - Template

#125 Section Middleware
  src/webapp/client/index.html
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
Labels: DocType - Code, Location - Client, Location - Server, Type - Enhancement

#126 Report on Course extension DB
  src/db/addCourseMgmt.sql
Labels: DocType - Code, Type - Enhancement

#131 Completes add a section
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
Labels: DocType - Code, Location - Server, Priority - High

#132 Report on Section Extension
  src/db/addSectionMgmt.sql
Labels: DocType - Code, Type - Enhancement

#136 Update the comments in the SQL scripts
  src/db/addCourseMgmt.sql
  src/db/addEnrolleeMgmt.sql
  src/db/addSectionMgmt.sql
Labels: DocType - Code

#140 Section instructor management
  src/webapp/client/index.html
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
Labels: DocType - Code, Location - Client, Location - Server, Priority - High

#143 Update the assignInstructor DB Function
  src/db/addSectionMgmt.sql
Labels: DocType - Code, Type - Enhancement

#144 Create Installation Guide
  docs/GradebookInstallationGuide.md
Labels: DocType - Documentation, Type - Enhancement

#145 Create gb user manual
  .gitignore
  docs/GradebookUserManual.md
  docs/UserManualImages/AddCourse.png
  docs/UserManualImages/AddSection.png
  docs/UserManualImages/AssignInstructors.png
  docs/UserManualImages/CourseManagement.png
  docs/UserManualImages/EditCourse.png
  docs/UserManualImages/EnrollStudent.png
  docs/UserManualImages/GradebookAfterLogin.png
  docs/UserManualImages/GradebookLogin.png
  docs/UserManualImages/Logout.png
  docs/UserManualImages/RemoveCourseOption1.png
  docs/UserManualImages/RemoveInstructors.png
  docs/UserManualImages/RemoveSection.png
  docs/UserManualImages/SectionManagement.png
Labels: DocType - Documentation, Type - Enhancement

#147 Dev Into Master
  .gitignore
  docs/GradebookInstallationGuide.md
  docs/GradebookUserManual.md
  docs/UserManualImages/AddCourse.png
  docs/UserManualImages/AddSection.png
  docs/UserManualImages/AssignInstructors.png
  docs/UserManualImages/CourseManagement.png
  docs/UserManualImages/EditCourse.png
  docs/UserManualImages/EnrollStudent.png
  docs/UserManualImages/GradebookAfterLogin.png
  docs/UserManualImages/GradebookLogin.png
  docs/UserManualImages/Logout.png
  docs/UserManualImages/RemoveCourseOption1.png
  docs/UserManualImages/RemoveInstructors.png
  docs/UserManualImages/RemoveSection.png
  docs/UserManualImages/SectionManagement.png
  src/db/addSectionMgmt.sql
Labels: DocType - Code, DocType - Documentation, Type - Enhancement

#148 Section management bug fixes
  src/db/addSectionMgmt.sql
  src/webapp/client/index.html
  src/webapp/client/js/index.js
  src/webapp/gradebookServer.js
Labels: Location - Client, Location - Server, Priority - High
